import type { IBook, IAuthor } from "../types/book";

// --- PLACEHOLDER FEATURED BOOKS ---
// Used so the hero carousel looks populated before real data exists
export const PLACEHOLDER_FEATURED: IBook[] = [
  {
    _id: "1",
    title: "CSS in Depth",
    author: "Keith J. Grant",
    authorName: "Keith J. Grant",
    description:
      "A comprehensive guide for web developers who want to go beyond the basics of CSS and master the intricacies of styling web pages. Designed for intermediate to advanced developers.",
    price: 29.99,
    discountPrice: undefined,
    coverImage:
      "https://m.media-amazon.com/images/I/71STjCNuKxL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 15000000,
    category: ["Web Development"],
    tags: ["css", "frontend"],
    rating: 4,
    reviewCount: 128,
    purchaseCount: 340,
    isFeatured: true,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "2",
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    authorName: "Kyle Simpson",
    description:
      "A deep dive into the core mechanisms of JavaScript. This book series challenges your assumptions and reveals the true nature of the language most developers think they already know.",
    price: 24.99,
    coverImage:
      "https://m.media-amazon.com/images/I/7186YfjgHHL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 8000000,
    category: ["JavaScript"],
    tags: ["javascript", "programming"],
    rating: 5,
    reviewCount: 312,
    purchaseCount: 890,
    isFeatured: true,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "3",
    title: "Clean Code",
    author: "Robert C. Martin",
    authorName: "Robert C. Martin",
    description:
      "A handbook of agile software craftsmanship. Even bad code can function, but if code isn't clean, it can bring a development organization to its knees. This book will make you a better programmer.",
    price: 34.99,
    discountPrice: 27.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71T7aD3EOTL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 12000000,
    category: ["Software Engineering"],
    tags: ["clean code", "best practices"],
    rating: 5,
    reviewCount: 540,
    purchaseCount: 1200,
    isFeatured: true,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "4",
    title: "The Pragmatic Programmer",
    author: "David Thomas & Andrew Hunt",
    authorName: "David Thomas & Andrew Hunt",
    description:
      "Your journey to mastery. Straight from the trenches, this book examines what it means to be a modern software developer. Packed with tips and tricks to make you more effective.",
    price: 32.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71VStSjZmpL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 10000000,
    category: ["Software Engineering"],
    tags: ["pragmatic", "career"],
    rating: 4,
    reviewCount: 280,
    purchaseCount: 760,
    isFeatured: true,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "5",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    authorName: "Martin Kleppmann",
    description:
      "The big ideas behind reliable, scalable, and maintainable systems. This book examines the pros and cons of various technologies for storing, processing and transforming data at scale.",
    price: 39.99,
    discountPrice: 31.99,
    coverImage:
      "https://m.media-amazon.com/images/I/91VWQN+2mkL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 20000000,
    category: ["System Design"],
    tags: ["databases", "distributed systems"],
    rating: 5,
    reviewCount: 610,
    purchaseCount: 1450,
    isFeatured: true,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
];

// --- PLACEHOLDER LATEST BOOKS ---
// Fills the "Latest Books" grid below the hero
export const PLACEHOLDER_LATEST: IBook[] = [
  ...PLACEHOLDER_FEATURED,
  {
    _id: "6",
    title: "System Design Interview",
    author: "Alex Xu",
    authorName: "Alex Xu",
    description: "An insider's guide to system design interviews.",
    price: 27.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71Rkbm4TK5L._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 11000000,
    category: ["System Design"],
    tags: ["interview", "system design"],
    rating: 4,
    reviewCount: 198,
    purchaseCount: 520,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "7",
    title: "Atomic Habits",
    author: "James Clear",
    authorName: "James Clear",
    description:
      "Tiny changes, remarkable results. The proven framework for building good habits.",
    price: 19.99,
    coverImage:
      "https://m.media-amazon.com/images/I/81wgcld4wxL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 7000000,
    category: ["Self-Help"],
    tags: ["habits", "productivity"],
    rating: 5,
    reviewCount: 890,
    purchaseCount: 2100,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "8",
    title: "Computer Science Distilled",
    author: "Wladston Ferreira Filho",
    authorName: "Wladston Ferreira Filho",
    description:
      "Learn the art of solving computational problems. A concise overview of CS concepts.",
    price: 22.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71yIScEkPJL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 9000000,
    category: ["Computer Science"],
    tags: ["cs fundamentals", "algorithms"],
    rating: 4,
    reviewCount: 156,
    purchaseCount: 430,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "9",
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    authorName: "Marijn Haverbeke",
    description:
      "A modern introduction to programming using JavaScript as the vehicle.",
    price: 21.99,
    coverImage:
      "https://m.media-amazon.com/images/I/51IKycqTPUL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 8500000,
    category: ["JavaScript"],
    tags: ["javascript", "beginner"],
    rating: 4,
    reviewCount: 234,
    purchaseCount: 670,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "10",
    title: "The Lean Startup",
    author: "Eric Ries",
    authorName: "Eric Ries",
    description:
      "How today's entrepreneurs use continuous innovation to create successful businesses.",
    price: 18.99,
    coverImage:
      "https://m.media-amazon.com/images/I/81-QB7nDh4L._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 6500000,
    category: ["Business"],
    tags: ["startup", "entrepreneurship"],
    rating: 4,
    reviewCount: 445,
    purchaseCount: 980,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
];

// --- PLACEHOLDER BOOKS ---
// Same as before — real data replaces this automatically
export const PLACEHOLDER_BOOKS: IBook[] = [
  {
    _id: "b1",
    title: "Atomic Habits",
    author: "James Clear",
    authorName: "James Clear",
    description: "Tiny changes, remarkable results.",
    price: 19.99,
    coverImage:
      "https://m.media-amazon.com/images/I/81wgcld4wxL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 7000000,
    category: ["Self-Help"],
    tags: ["habits"],
    rating: 5,
    reviewCount: 890,
    purchaseCount: 2100,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b2",
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    authorName: "Douglas Crockford",
    description: "Unearthing the excellence in JavaScript.",
    price: 22.99,
    coverImage:
      "https://m.media-amazon.com/images/I/7168pezvDQL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 5000000,
    category: ["JavaScript"],
    tags: ["javascript"],
    rating: 4,
    reviewCount: 340,
    purchaseCount: 870,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b3",
    title: "Algorithms",
    author: "Robert Sedgewick",
    authorName: "Robert Sedgewick",
    description: "The gold standard for algorithm textbooks.",
    price: 44.99,
    discountPrice: 34.99,
    coverImage:
      "https://m.media-amazon.com/images/I/61-OQE7zLzL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 25000000,
    category: ["Computer Science"],
    tags: ["algorithms"],
    rating: 5,
    reviewCount: 512,
    purchaseCount: 1300,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b4",
    title: "Fundamentals of Database Systems",
    author: "Ramez Elmasri",
    authorName: "Ramez Elmasri",
    description: "The definitive guide to database design.",
    price: 49.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71YIszjdolL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 30000000,
    category: ["Computer Science"],
    tags: ["databases"],
    rating: 4,
    reviewCount: 210,
    purchaseCount: 560,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b5",
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    authorName: "Marijn Haverbeke",
    description: "A modern introduction to programming.",
    price: 21.99,
    coverImage:
      "https://m.media-amazon.com/images/I/51IKycqTPUL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 8500000,
    category: ["JavaScript"],
    tags: ["javascript", "beginner"],
    rating: 4,
    reviewCount: 234,
    purchaseCount: 670,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b6",
    title: "The Clean Coder",
    author: "Robert C. Martin",
    authorName: "Robert C. Martin",
    description: "A code of conduct for professional programmers.",
    price: 29.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71T7aD3EOTL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 12000000,
    category: ["Software Engineering"],
    tags: ["clean code"],
    rating: 5,
    reviewCount: 445,
    purchaseCount: 1100,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b7",
    title: "Operating System Concepts",
    author: "Abraham Silberschatz",
    authorName: "Abraham Silberschatz",
    description: "The definitive OS textbook.",
    price: 54.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71RkubHDDkL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 35000000,
    category: ["Computer Science"],
    tags: ["operating systems"],
    rating: 4,
    reviewCount: 310,
    purchaseCount: 780,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b8",
    title: "The Lean Startup",
    author: "Eric Ries",
    authorName: "Eric Ries",
    description: "How entrepreneurs use continuous innovation.",
    price: 18.99,
    coverImage:
      "https://m.media-amazon.com/images/I/81-QB7nDh4L._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 6500000,
    category: ["Business"],
    tags: ["startup"],
    rating: 4,
    reviewCount: 445,
    purchaseCount: 980,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b9",
    title: "Seriously Good Software",
    author: "Marco Faella",
    authorName: "Marco Faella",
    description: "Code that works, survives, and wins.",
    price: 35.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71yIScEkPJL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 14000000,
    category: ["Software Engineering"],
    tags: ["software quality"],
    rating: 4,
    reviewCount: 98,
    purchaseCount: 230,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b10",
    title: "HTML and CSS",
    author: "Jon Duckett",
    authorName: "Jon Duckett",
    description: "Design and build websites.",
    price: 26.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71Rkbm4TK5L._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 18000000,
    category: ["Web Development"],
    tags: ["html", "css"],
    rating: 4,
    reviewCount: 567,
    purchaseCount: 1450,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b11",
    title: "The Art of 64-Bit Assembly",
    author: "Randall Hyde",
    authorName: "Randall Hyde",
    description: "Master 64-bit assembly language programming.",
    price: 42.99,
    coverImage:
      "https://m.media-amazon.com/images/I/7168pezvDQL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 22000000,
    category: ["Programming"],
    tags: ["assembly"],
    rating: 4,
    reviewCount: 87,
    purchaseCount: 190,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b12",
    title: "System Design Interview",
    author: "Alex Xu",
    authorName: "Alex Xu",
    description: "An insider's guide to system design interviews.",
    price: 27.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71Rkbm4TK5L._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 11000000,
    category: ["System Design"],
    tags: ["interview"],
    rating: 4,
    reviewCount: 198,
    purchaseCount: 520,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b13",
    title: "Designing Data-Intensive Apps",
    author: "Martin Kleppmann",
    authorName: "Martin Kleppmann",
    description: "Reliable, scalable, and maintainable systems.",
    price: 39.99,
    discountPrice: 31.99,
    coverImage:
      "https://m.media-amazon.com/images/I/91VWQN+2mkL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 20000000,
    category: ["System Design"],
    tags: ["databases"],
    rating: 5,
    reviewCount: 610,
    purchaseCount: 1450,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b14",
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    authorName: "Kyle Simpson",
    description: "A deep dive into the core mechanisms of JavaScript.",
    price: 24.99,
    coverImage:
      "https://m.media-amazon.com/images/I/7186YfjgHHL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "epub",
    fileSize: 8000000,
    category: ["JavaScript"],
    tags: ["javascript"],
    rating: 5,
    reviewCount: 312,
    purchaseCount: 890,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "b15",
    title: "Clean Code",
    author: "Robert C. Martin",
    authorName: "Robert C. Martin",
    description: "A handbook of agile software craftsmanship.",
    price: 34.99,
    discountPrice: 27.99,
    coverImage:
      "https://m.media-amazon.com/images/I/71T7aD3EOTL._AC_UF1000,1000_QL80_.jpg",
    fileUrl: "",
    fileType: "pdf",
    fileSize: 12000000,
    category: ["Software Engineering"],
    tags: ["clean code"],
    rating: 5,
    reviewCount: 540,
    purchaseCount: 1200,
    isFeatured: false,
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
];

// --- PLACEHOLDER AUTHORS ---
export const PLACEHOLDER_AUTHORS: IAuthor[] = [
  {
    _id: "1",
    name: "Robert C. Martin",
    bio: "Robert C. Martin, known as Uncle Bob, is a renowned software engineer and author. He is co-author of the Agile Manifesto and has written some of the most influential books in software engineering.",
    avatar:
      "https://m.media-amazon.com/images/I/71T7aD3EOTL._AC_UF1000,1000_QL80_.jpg",
    specialty: ["Software Engineering", "Clean Code", "Agile"],
    nationality: "American",
    website: "https://cleancoder.com",
    socialLinks: { twitter: "https://twitter.com/unclebobmartin" },
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "2",
    name: "Martin Kleppmann",
    bio: "Martin Kleppmann is a researcher at Cambridge and author of Designing Data-Intensive Applications. He works on distributed systems, CRDTs, and data infrastructure.",
    avatar:
      "https://m.media-amazon.com/images/I/91VWQN+2mkL._AC_UF1000,1000_QL80_.jpg",
    specialty: ["Distributed Systems", "Databases", "System Design"],
    nationality: "German",
    website: "https://martin.kleppmann.com",
    socialLinks: { twitter: "https://twitter.com/martinkl" },
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "3",
    name: "Kyle Simpson",
    bio: "Kyle Simpson, known as getify, is a JavaScript author, speaker, and educator. He is the author of the You Don't Know JS book series and is passionate about making JavaScript accessible.",
    avatar:
      "https://m.media-amazon.com/images/I/7186YfjgHHL._AC_UF1000,1000_QL80_.jpg",
    specialty: ["JavaScript", "Web Development", "Programming"],
    nationality: "American",
    website: "https://github.com/getify",
    socialLinks: {
      twitter: "https://twitter.com/getify",
      github: "https://github.com/getify",
    },
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "4",
    name: "Andrew Hunt",
    bio: "Andrew Hunt is co-author of The Pragmatic Programmer and a founding member of the Agile Alliance. He has spent decades helping developers build better software.",
    avatar:
      "https://m.media-amazon.com/images/I/71VStSjZmpL._AC_UF1000,1000_QL80_.jpg",
    specialty: ["Software Craftsmanship", "Agile", "Career Development"],
    nationality: "American",
    website: "https://pragprog.com",
    socialLinks: {},
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "5",
    name: "Eric Ries",
    bio: "Eric Ries is the author of The Lean Startup and a pioneer of the lean startup methodology. He has advised hundreds of startups and large companies on how to build products efficiently.",
    avatar:
      "https://m.media-amazon.com/images/I/81-QB7nDh4L._AC_UF1000,1000_QL80_.jpg",
    specialty: ["Business", "Startups", "Product Management"],
    nationality: "American",
    website: "https://theleanstartup.com",
    socialLinks: { twitter: "https://twitter.com/ericries" },
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "6",
    name: "James Clear",
    bio: "James Clear is the author of Atomic Habits, one of the best-selling books of the decade. He writes about habits, decision making, and continuous improvement.",
    avatar:
      "https://m.media-amazon.com/images/I/81wgcld4wxL._AC_UF1000,1000_QL80_.jpg",
    specialty: ["Self-Help", "Habits", "Productivity"],
    nationality: "American",
    website: "https://jamesclear.com",
    socialLinks: { twitter: "https://twitter.com/jamesclear" },
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "7",
    name: "Alex Xu",
    bio: "Alex Xu is the author of the System Design Interview series. He has worked at Twitter, Apple, and Zynga and is passionate about helping engineers ace system design interviews.",
    avatar:
      "https://m.media-amazon.com/images/I/71Rkbm4TK5L._AC_UF1000,1000_QL80_.jpg",
    specialty: ["System Design", "Software Architecture", "Interviews"],
    nationality: "American",
    website: "https://bytebytego.com",
    socialLinks: { linkedin: "https://linkedin.com/in/alexxu" },
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "8",
    name: "Marijn Haverbeke",
    bio: "Marijn Haverbeke is a open source developer and author of Eloquent JavaScript. He has built tools like CodeMirror and ProseMirror that power editors across the web.",
    avatar:
      "https://m.media-amazon.com/images/I/51IKycqTPUL._AC_UF1000,1000_QL80_.jpg",
    specialty: ["JavaScript", "Programming Languages", "Open Source"],
    nationality: "Dutch",
    website: "https://marijnhaverbeke.nl",
    socialLinks: { github: "https://github.com/marijnh" },
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
];

// --- PLACEHOLDER REVIEWS ---
// Real reviews come in Phase 5 — these make the tab look populated now
export const PLACEHOLDER_REVIEWS = [
  {
    id: "1",
    name: "Sarah K.",
    avatar: "",
    rating: 5,
    date: "March 2025",
    comment:
      "Absolutely loved this book. Clear explanations, great examples, and very practical. I finished it in a week and immediately applied the concepts at work.",
  },
  {
    id: "2",
    name: "James R.",
    avatar: "",
    rating: 4,
    date: "February 2025",
    comment:
      "Really solid book. The writing is concise and to the point. A few sections felt rushed but overall a fantastic read that I would recommend to any developer.",
  },
  {
    id: "3",
    name: "Aisha M.",
    avatar: "",
    rating: 5,
    date: "January 2025",
    comment:
      "One of the best technical books I have read this year. The author explains complex concepts in a way that is easy to understand even for beginners.",
  },
  {
    id: "4",
    name: "David L.",
    avatar: "",
    rating: 4,
    date: "December 2024",
    comment:
      "Great content and well structured. I especially liked the practical examples throughout the chapters. Would definitely buy more books from this author.",
  },
  {
    id: "5",
    name: "Priya S.",
    avatar: "",
    rating: 5,
    date: "November 2024",
    comment:
      "This book changed how I approach my work. Highly recommend to anyone who wants to level up their skills and think more systematically.",
  },
];

// Placeholder video — a royalty-free library/reading themed video
export const PLACEHOLDER_VIDEO = "https://www.w3schools.com/html/mov_bbb.mp4";

// Single source of truth for all placeholder books
// Any book clicked anywhere in the app will be found here
export const ALL_PLACEHOLDERS: IBook[] = [
  ...PLACEHOLDER_FEATURED,
  ...PLACEHOLDER_LATEST.filter(
    (b) => !PLACEHOLDER_FEATURED.find((f) => f._id === b._id),
  ),
  ...PLACEHOLDER_BOOKS.filter(
    (b) =>
      !PLACEHOLDER_FEATURED.find((f) => f._id === b._id) &&
      !PLACEHOLDER_LATEST.find((l) => l._id === b._id),
  ),
];
