export const BOOK_CATEGORY_BUCKETS = {
  fiction: [
    "Literary Fiction",
    "Contemporary Fiction",
    "Contemporary Literary Fiction",
    "Realism",
  ],
  "fantasy-adventure": [
    "Fantasy",
    "Epic Fantasy",
    "Adventure",
    "Adventure Fiction",
  ],
  classics: ["Classics", "Classic Literature"],
  romance: [
    "Romance",
    "Comedy",
    "Romantic Comedy",
    "Romantic Drama",
    "Comedy Drama",
    "Melodrama",
    "Slice of Life",
  ],
  "mystery-thriller": [
    "Crime",
    "Crime Fiction",
    "Suspense",
    "Detective Fiction",
    "Murder Mystery",
    "Mystery",
    "Thriller",
    "Surveillance Thriller",
    "Psychological Thriller",
    "Psychological Fiction",
  ],
  "sci-fi-dystopian": [
    "Science Fiction",
    "Social Science Fiction",
    "Dystopian Fiction",
    "Apocalyptic Fiction",
  ],
  "historical-fiction": ["Historical Fiction", "Political Fiction"],
  "business-finance": ["Business", "Finance"],
  "psychology-self-help": ["Psychology", "Self-Help", "Personal Development"],
  philosophy: ["Philosophy", "Philosophical Fiction", "Political Satire"],
  biography: ["Biography", "Memoir", "Autobiography"],
  science: ["Science", "Astronomy", "Physics", "Cosmology"],
  technology: ["Technology", "Programming", "Computer Science"],
  history: ["History"],
} as const;

export type BookCategoryBucketKey = keyof typeof BOOK_CATEGORY_BUCKETS;
