export const BOOK_CATEGORY_BUCKETS = {
  fiction: [
    "Literary Fiction",
    "Contemporary Fiction",
    "Contemporary Literary Fiction",
    "Realism",
  ],
  "fantasy-adventure": ["Fantasy", "Epic Fantasy", "Adventure Fiction"],
  classics: ["Classics", "Classic Literature"],
  "romance-comedy": [
    "Romance",
    "Comedy",
    "Romantic Comedy",
    "Romantic Drama",
    "Comedy Drama",
    "Melodrama",
    "Slice of Life",
  ],
  "mystery-crime": [
    "Crime",
    "Crime Fiction",
    "Suspense",
    "Detective Fiction",
    "Murder Mystery",
    "Mystery",
    "Surveillance Thriller",
    "Psychological Fiction",
  ],
  "sci-fi-dystopian": [
    "Science Fiction",
    "Social Science Fiction",
    "Dystopian Fiction",
    "Apocalyptic Fiction",
    "Epic Fiction",
    "Epic Fantasy",
  ],
  "historical-fiction": ["Historical Fiction", "Political Fiction"],
  "business-finance": ["Business", "Finance"],
  "psychology-self-help": ["Psychology", "Self-Help", "Personal Development"],
  philosophy: ["Philosophy", "Philosophical Fiction", "Political Satire"],
  science: ["Science", "Astronomy"],
  history: ["History"],
} as const;

export type BookCategoryBucketKey = keyof typeof BOOK_CATEGORY_BUCKETS;
